const wordList = [
    "abandon", "abbreviate", "abhorrence", "abrasive", "absurd", "accelerate", "accessible", "accommodate", "accomplice", "accumulate",
    "accuracy", "achieve", "acknowledge", "acquisition", "adjacent", "admiration", "adolescent", "adversary", "advocate", "aesthetic",
    "affirmation", "aggravate", "allegiance", "ambiguous", "ameliorate", "amplify", "ancestor", "anguish", "announcement", "anonymous",
    "anticipate", "apprehensive", "argumentative", "ascendancy", "assessment", "assimilate", "astounding", "atrocious", "authentic",
    "authority", "avidity", "banish", "beneficial", "biodegradable", "blatant", "bolster", "brevity", "calculate", "camouflage",
    "capitulate", "captivate", "category", "cautious", "celebrate", "censure", "challenge", "changeable", "charismatic", "chastise",
    "chronic", "cliché", "coalesce", "collaborate", "commemorate", "communication", "comparable", "compassion", "compensate", "competence",
    "comprehend", "concede", "conceivable", "conclusive", "concur", "condemn", "condescend", "conducive", "confrontation", "congenial",
    "consequence", "consistent", "conspicuous", "contemplate", "contradict", "controversial", "convergence", "correspond", "corroborate",
    "credible", "culminate", "cumbersome", "debase", "deceive", "decipher", "decompose", "decorum", "deferential", "deficient", "delectable",
    "deliberate", "denounce", "derive", "desolate", "despise", "deteriorate", "detrimental", "devastate", "deviate", "diagnose", "dilemma",
    "diligent", "diminish", "discreet", "disparate", "dissent", "distinctive", "diversion", "divulge", "eccentric", "eclectic", "elicit",
    "elude", "embellish", "embolden", "empathize", "endorse", "enhance", "enigma", "enrapture", "entice", "enunciate", "epiphany",
    "eradicate", "escalate", "esoteric", "essential", "evocative", "exacerbate", "exalt", "exemplify", "expeditious", "exquisite",
    "extol", "extricate", "facetious", "fallacy", "fathom", "feasible", "ferocious", "fiasco", "fluctuate", "formidable", "frivolous",
    "galvanize", "garrulous", "generation", "genuine", "gesticulate", "glorious", "gracious", "grandiose", "gravitate", "gregarious",
    "guileless", "harangue", "harbinger", "haughty", "hedonistic", "hereditary", "hesitate", "homogeneous", "humility", "hyperbole",
    "hypocritical", "immaculate", "imminent", "impartial", "implement", "implore", "inaugurate", "incessant", "inchoate", "incongruous",
    "incorrigible", "incumbent", "indelible", "indigenous", "indignant", "indispensable", "ineffable", "inevitable", "infamous", "infatuation",
    "infiltrate", "inherent", "innate", "innocuous", "inquisitive", "insatiable", "inscrutable", "insidious", "insinuate", "insipid",
    "insolent", "integrate", "integrity", "intrepid", "inundate", "invincible", "irrefutable", "irresistible", "itinerant", "juxtapose",
    "kindle", "kinetic", "lackadaisical", "lament", "languish", "lassitude", "lavish", "legacy", "lenient", "lethargic", "levitate",
    "liaison", "loquacious", "lucid", "ludicrous", "magnanimous", "malicious", "manifest", "manipulate", "meander", "mediocre", "melancholy",
    "metamorphosis", "methodical", "meticulous", "mitigate", "modulate", "multifaceted", "mundane", "nefarious", "negligent", "nostalgic",
    "notorious", "novice", "nuance", "obliterate", "obnoxious", "obscure", "obsolete", "obstinate", "ominous", "opulent", "oscillate",
    "ostracize", "overwhelm", "palpable", "panacea", "paradox", "paramount", "pensive", "perceptive", "persevere", "pervasive", "pious",
    "plausible", "ponder", "pragmatic", "precarious", "predicament", "prejudice", "profound", "prohibitive", "prolific", "prosaic", "prudent",
    "pungent", "quandary", "quell", "quixotic", "rambunctious", "reclusive", "redundant", "reflective", "rejuvenate", "relinquish",
    "remediate", "renaissance", "reprehensible", "resilient", "resolution", "resonate", "rigorous", "salient", "sanction", "savor",
    "scrupulous", "scurrilous", "serendipity", "serene", "sever", "shimmer", "simulate", "soothe", "spontaneity", "stagnant", "stealthy",
    "strive", "sublime", "succinct", "supercilious", "superfluous", "surmise", "surreptitious", "sycophant", "symbiotic", "synthesize",
    "tangible", "tantalize", "tenacious",
    "abase", "accolade", "acrimonious", "adamant", "adulation", "aesthetic", "alacrity", "allay", "aloof", "altruistic",
    "ambivalent", "amiable", "anachronistic", "antipathy", "apocryphal", "arduous", "assuage", "astute", "augment", "aversion",
    "belie", "belligerent", "bequeath", "blithe", "bombastic", "cacophony", "capitulate", "castigate", "chicanery", "coalesce",
    "confluence", "conundrum", "convivial", "copious", "craven", "debilitate", "debunk", "decimate", "deference", "delineate",
    "denigrate", "depravity", "desecrate", "diatribe", "didactic", "disparate", "dissemble", "ebullient", "efface", "effervescent",
    "egregious", "eloquent", "emulate", "enervate", "enmity", "ennui", "ephemeral", "equanimity", "equivocate", "eschew",
    "evanescent", "exacerbate", "exculpate", "exonerate", "expunge", "extol", "fastidious", "felicitous", "flabbergasted",
    "foment", "garrulous", "gratuitous", "gregarious", "harangue", "harbinger", "heinous", "iconoclast", "impetuous", "ineffable",
    "inexorable", "insidious", "intransigent", "ineffable", "inscrutable", "insipid", "intransigent", "inveterate", "juxtapose",
    "lament", "languid", "lethargic", "loquacious", "maudlin", "maverick", "mollify", "mordant", "munificent", "nebulous",
    "nefarious", "neophyte", "obfuscate", "obsequious", "obtuse", "odious", "onerous", "palpable", "pernicious", "platitude",
    "portent", "precarious", "precocious", "predilection", "propensity", "quagmire", "quell", "quixotic", "quotidian", "raucous",
    "relegate", "repudiate", "rescind", "reticent", "sardonic", "serendipity", "sycophant", "taciturn", "trepidation", "ubiquitous",
    "unctuous", "vacillate", "vehement", "verbose", "vestige", "vilify", "vitriolic", "vivacious", "volatile", "wary", "wistful",
    "wry", "zealous", "zenith", "zephyr", "quotidian", "raucous", "redolent"
  ]
  
      